In [1]:
import numpy as np

In [2]:
bbox = np.load('/svl/u/redfairy/datasets/data_bbox/slider_drawer_40417_3_sdf_bbox.npy')

In [3]:
print(bbox)

[[ 0.25323437  0.09881135 -0.21140676]
 [ 0.25323434  0.09881138  0.21140677]
 [-0.25323437  0.09881138  0.21140674]
 [-0.25323434  0.09881135 -0.21140679]
 [ 0.25323437 -0.09881138 -0.21140674]
 [ 0.25323434 -0.09881135  0.21140679]
 [-0.25323437 -0.09881135  0.21140676]
 [-0.25323434 -0.09881138 -0.21140677]]
